name: Build

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
  build:
    timeout-minutes: 15
    continue-on-error: true
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - name: Build
        run: zig build
      - name: Test
        run: zig build test
  # ubuntu-build:
  #   timeout-minutes: 15
  #   continue-on-error: true
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: goto-bus-stop/setup-zig@v2
  #     - name: Install OpenGL
  #       run: apt-get libglu1-mesa-dev freeglut3-dev mesa-common-dev
  #     - name: Build
  #       run: zig build
  #     - name: Test
  #       run: zig build test
  lint:
    needs: build
    timeout-minutes: 15
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig fmt --check .